COMPANIES = [
    {
        "name": "Affirm",
        "brand_color": "#4A4AF4",
        "careers_url": "https://www.affirm.com/careers#jobOpenings",
        "ats": "greenhouse",
        "board_id": "affirm",
    },
    {
        "name": "Coinbase",
        "brand_color": "#0052FF",
        "careers_url": "https://www.coinbase.com/careers/positions",
        "ats": "greenhouse",
        "board_id": "coinbase",
    },
    {
        "name": "Microsoft",
        "brand_color": "#00A4EF",
        # URL pre-filtered: US, remote, entry/mid-level, engineering + security departments
        "careers_url": "https://apply.careers.microsoft.com/careers?start=0&location=United+States&pid=1970393556834529&sort_by=match&filter_include_remote=1&filter_work_site=0+days+%2F+week+in-office+%E2%80%93+remote&filter_seniority=Mid-Level%2CEntry",
        "ats": "eightfold",
    },
    {
        "name": "Netflix",
        "brand_color": "#E50914",
        "careers_url": "https://explore.jobs.netflix.net/careers?location=Remote&domain=netflix.com&sort_by=new",
        "ats": "eightfold_v2",
    },
    {
        "name": "Dropbox",
        "brand_color": "#0061FF",
        "careers_url": "https://www.dropbox.jobs/en/jobs/",
        "ats": "greenhouse",
        "board_id": "dropbox",
    },
    {
        "name": "Reddit",
        "brand_color": "#FF4500",
        "careers_url": "https://redditinc.com/careers",
        "ats": "greenhouse",
        "board_id": "reddit",
    },
    {
        "name": "Airbnb",
        "brand_color": "#FF5A5F",
        "careers_url": "https://careers.airbnb.com/positions/?_where_you_work=united-states&_workplace_type=live-and-work-anywhere",
        "ats": "greenhouse",
        "board_id": "airbnb",
    },
    {
        "name": "Stripe",
        "brand_color": "#635BFF",
        "careers_url": "https://stripe.com/jobs/search?remote_locations=North+America--US+Remote",
        "ats": "greenhouse",
        "board_id": "stripe",
    },
    {
        "name": "GitLab",
        "brand_color": "#FC6D26",
        "careers_url": "https://about.gitlab.com/jobs/all-jobs/",
        "ats": "greenhouse",
        "board_id": "gitlab",
    },
    {
        "name": "CrowdStrike",
        "brand_color": "#E01E2D",
        # Pre-filtered: US only (locationCountry), Engineering/Security/SRE job families
        "careers_url": "https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers?locationCountry=bc33aa3152ec42d4995f4791a106ed09&Job_Family=1408861ee6e20197f95adbf6b000d20b&Job_Family=cb19f044639b1001f6a02595bc920000&Job_Family=1408861ee6e201b287b816f7b000020c",
        "ats": "workday",
    },
    {
        "name": "GitHub",
        "brand_color": "#F0F6FC",
        # tags6=Remote selects remote roles; locations=,,United States filters to US
        "careers_url": "https://www.github.careers/careers-home/jobs?tags6=Remote&locations=,,United%20States",
        "ats": "icims_phenom",
    },
    {
        "name": "Mozilla",
        "brand_color": "#FF7139",
        "careers_url": "https://www.mozilla.org/en-US/careers/listings/",
        "ats": "greenhouse",
        "board_id": "mozilla",
    },
    {
        "name": "Circle",
        "brand_color": "#2775CA",
        "careers_url": "https://circle.wd1.myworkdayjobs.com/en-US/Circle",
        "ats": "workday",
    },
    {
        "name": "NerdWallet",
        "brand_color": "#8CC63F",
        "careers_url": "https://www.nerdwallet.com/careers/jobs",
        "ats": "ashby",
        "board_id": "nerdwallet",
    },
    {
        "name": "Confluent",
        "brand_color": "#00AFBA",
        "careers_url": "https://careers.confluent.io/jobs",
        "ats": "ashby",
        "board_id": "confluent",
    },
    {
        "name": "Zillow",
        "brand_color": "#006AFF",
        # Pre-filtered: remote US, full-time, engineering & software job families
        "careers_url": "https://zillow.wd5.myworkdayjobs.com/Zillow_Group_External?locations=bf3166a9227a01f8b514f0b00b147bc9&locations=76d84517207210c0ae0449a1ba82e635&timeType=156fb9a2f01c10be203b6e91581a01d1&workerSubType=156fb9a2f01c10bed80e140d011a9559&jobFamilyGroup=a90eab1aaed6105e8dd41df427a82ee6&jobFamilyGroup=a90eab1aaed6105e8dcac61d33c32ee2",
        "ats": "workday",
    },
    {
        "name": "Instacart",
        "brand_color": "#43B02A",
        "careers_url": "https://www.instacart.careers/current-openings",
        "ats": "greenhouse",
        "board_id": "instacart",
    },
    {
        "name": "Quora",
        "brand_color": "#B92B27",
        "careers_url": "https://jobs.ashbyhq.com/quora",
        "ats": "ashby",
        "board_id": "quora",
    },
    {
        "name": "Twilio",
        "brand_color": "#F22F46",
        "careers_url": "https://jobs.twilio.com/careers",
        "ats": "greenhouse",
        "board_id": "twilio",
    },
    {
        "name": "Zoom",
        "brand_color": "#2D8CFF",
        # Pre-filtered: US remote, Engineering + Security + IT categories
        "careers_url": "https://careers.zoom.us/jobs/search?remote=true&category_uids%5B%5D=0f7d801c7a66e8c1a8f080f51aa2ddcb&category_uids%5B%5D=b79264f5877fa58df2bb612887751822&category_uids%5B%5D=a48a669452cc4488c0b5d6fcfb5a597a&country_codes%5B%5D=US&query=",
        "ats": "clinchtalent",
    },
    {
        "name": "Zscaler",
        "brand_color": "#0096D6",
        "careers_url": "https://www.zscaler.com/careers/search",
        "ats": "greenhouse",
        "board_id": "zscaler",
    },
    {
        "name": "Oura",
        "brand_color": "#D6B46C",
        "careers_url": "https://job-boards.greenhouse.io/oura",
        "ats": "greenhouse",
        "board_id": "oura",
    },
    {
        "name": "Wiz",
        "brand_color": "#8B5CF6",
        "careers_url": "https://www.wiz.io/careers",
        "ats": "greenhouse",
        "board_id": "wizinc",
    },
    {
        "name": "Rubrik",
        "brand_color": "#F26322",
        "careers_url": "https://www.rubrik.com/company/careers",
        "ats": "greenhouse",
        "board_id": "rubrik",
    },
    {
        "name": "Databricks",
        "brand_color": "#FF3621",
        "careers_url": "https://www.databricks.com/company/careers/open-positions",
        "ats": "greenhouse",
        "board_id": "databricks",
    },
    {
        "name": "Elastic",
        "brand_color": "#00BFB3",
        "careers_url": "https://www.elastic.co/about/careers",
        "ats": "greenhouse",
        "board_id": "elastic",
    },
    {
        "name": "SailPoint",
        "brand_color": "#00B2A9",
        # Pre-filtered: Engineering department only
        "careers_url": "https://sailpoint.wd1.myworkdayjobs.com/en-US/SailPoint?jobFamilyGroup=b0d5a0c394c810a2b2b41b6251e64819",
        "ats": "workday",
        "us_only": True,
    },
    {
        "name": "Snowflake",
        "brand_color": "#29B5E8",
        "careers_url": "https://careers.snowflake.com/us/en",
        "ats": "ashby",
        "board_id": "snowflake",
    },
    {
        "name": "Plaid",
        "brand_color": "#F5F7FA",
        "careers_url": "https://plaid.com/careers/",
        "ats": "ashby",
        "board_id": "plaid",
    },
    {
        "name": "Brex",
        "brand_color": "#FF5A1F",
        "careers_url": "https://www.brex.com/careers",
        "ats": "greenhouse",
        "board_id": "brex",
        "us_only": True,
    },
    {
        "name": "Figma",
        "brand_color": "#A259FF",
        "careers_url": "https://www.figma.com/careers/",
        "ats": "greenhouse",
        "board_id": "figma",
    },
    {
        "name": "HubSpot",
        "brand_color": "#FF7A59",
        "careers_url": "https://www.hubspot.com/careers/jobs",
        "ats": "greenhouse",
        "board_id": "hubspotjobs",
    },
    {
        "name": "Abnormal Security",
        "brand_color": "#8B5CF6",
        "careers_url": "https://abnormalsecurity.com/about/careers",
        "ats": "greenhouse",
        "board_id": "abnormalsecurity",
    },
    {
        "name": "Grafana Labs",
        "brand_color": "#F46800",
        "careers_url": "https://grafana.com/about/careers/",
        "ats": "greenhouse",
        "board_id": "grafanalabs",
    },
    {
        "name": "Tenable",
        "brand_color": "#00B3B8",
        "careers_url": "https://www.tenable.com/careers",
        "ats": "greenhouse",
        "board_id": "tenableinc",
    },
    {
        "name": "1Password",
        "brand_color": "#0572EC",
        "careers_url": "https://jobs.ashbyhq.com/1password",
        "ats": "ashby",
        "board_id": "1password",
    },
    {
        "name": "Vanta",
        "brand_color": "#8B5CF6",
        "careers_url": "https://www.vanta.com/careers",
        "ats": "ashby",
        "board_id": "vanta",
    },
    {
        "name": "Drata",
        "brand_color": "#7C5CFC",
        "careers_url": "https://drata.com/company/careers",
        "ats": "ashby",
        "board_id": "drata",
    },
    {
        "name": "Pinterest",
        "brand_color": "#E60023",
        "careers_url": "https://www.pinterestcareers.com/jobs/",
        "ats": "greenhouse",
        "board_id": "pinterest",
    },
    {
        "name": "DoorDash",
        "brand_color": "#FF3008",
        "careers_url": "https://job-boards.greenhouse.io/doordashusa",
        "ats": "greenhouse",
        "board_id": "doordashusa",
    },
    {
        "name": "OpenAI",
        "brand_color": "#10A37F",
        "careers_url": "https://jobs.ashbyhq.com/openai",
        "ats": "ashby",
        "board_id": "openai",
    },
    {
        "name": "Tailscale",
        "brand_color": "#F4F4F5",
        "careers_url": "https://job-boards.greenhouse.io/tailscale",
        "ats": "greenhouse",
        "board_id": "tailscale",
    },
    {
        "name": "MongoDB",
        "brand_color": "#00ED64",
        "careers_url": "https://www.mongodb.com/careers/jobs",
        "ats": "greenhouse",
        "board_id": "mongodb",
    },
    {
        "name": "Chime",
        "brand_color": "#00D64F",
        "careers_url": "https://boards.greenhouse.io/chime",
        "ats": "greenhouse",
        "board_id": "chime",
    },
    {
        "name": "Discord",
        "brand_color": "#5865F2",
        "careers_url": "https://discord.com/jobs",
        "ats": "greenhouse",
        "board_id": "discord",
    },
    {
        "name": "Samsara",
        "brand_color": "#FF5C35",
        "careers_url": "https://www.samsara.com/company/careers/roles",
        "ats": "greenhouse",
        "board_id": "samsara",
    },
    {
        "name": "Temporal",
        "brand_color": "#8B5CF6",
        "careers_url": "https://temporal.io/careers",
        "ats": "ashby",
        "board_id": "temporal",
    },
    {
        "name": "Mercury",
        "brand_color": "#8C6FF7",
        "careers_url": "https://mercury.com/jobs",
        "ats": "greenhouse",
        "board_id": "mercury",
    },
    {
        "name": "Vercel",
        "brand_color": "#FFFFFF",
        "careers_url": "https://job-boards.greenhouse.io/vercel",
        "ats": "greenhouse",
        "board_id": "vercel",
    },
    {
        "name": "ClickHouse",
        "brand_color": "#FFCC01",
        "careers_url": "https://clickhouse.com/company/careers",
        "ats": "ashby",
        "board_id": "clickhouse",
    },
    {
        "name": "LaunchDarkly",
        "brand_color": "#405BFF",
        "careers_url": "https://job-boards.greenhouse.io/launchdarkly",
        "ats": "greenhouse",
        "board_id": "launchdarkly",
    },
    {
        "name": "OpenRouter",
        "brand_color": "#7C83FF",
        "careers_url": "https://jobs.ashbyhq.com/openrouter",
        "ats": "ashby",
        "board_id": "openrouter",
    },
    {
        "name": "Render",
        "brand_color": "#46E3B7",
        "careers_url": "https://jobs.ashbyhq.com/render",
        "ats": "ashby",
        "board_id": "render",
    },
    {
        "name": "WorkOS",
        "brand_color": "#6366F1",
        "careers_url": "https://jobs.ashbyhq.com/workos",
        "ats": "ashby",
        "board_id": "workos",
    },
    {
        "name": "Modern Treasury",
        "brand_color": "#2D6CDF",
        "careers_url": "https://jobs.ashbyhq.com/moderntreasury",
        "ats": "ashby",
        "board_id": "moderntreasury",
    },
    {
        "name": "Omni",
        "brand_color": "#8B5CF6",
        "careers_url": "https://jobs.ashbyhq.com/omni",
        "ats": "ashby",
        "board_id": "omni",
    },
    {
        "name": "Centralize",
        "brand_color": "#22D3EE",
        "careers_url": "https://jobs.ashbyhq.com/centralize",
        "ats": "ashby",
        "board_id": "centralize",
    },
]

# Job titles containing any of these are excluded (case-insensitive)
TITLE_EXCLUDE_KEYWORDS = [
    "principal",
    "staff",
    "director",
    "architect",
    "manager",
    "senior"
]

# Job title must contain at least one of these (case-insensitive)
TITLE_KEYWORDS = [
    "software engineer",
    "software developer",
    "software development engineer",
    "security engineer",
    "IAM",
    "identity and access",
    "identity access",
    "platform engineer",
    "backend engineer",
    "frontend engineer",
    "frontend developer",
    "full stack",
    "fullstack",
    "site reliability",
    "SRE",
    "devops",
    "infrastructure engineer",
    "identity engineer",
]

# Location/title/description must contain at least one of these (case-insensitive)
REMOTE_KEYWORDS = [
    "remote",
    "anywhere",
    "distributed",
    "work from home",
    "wfh",
    "us-based",
    "east coast",
    "west coast",
]
